### ISSUE TITLE
Missing scripts in example

### ISSUE THREAD

**Issue by akhilles** [aerospike/aerospike-kubernetes#20]
The links for `on-start.sh` and `install.sh` are broken at https://github.com/aerospike/aerospike-kubernetes/tree/master/examples/storage-engine-device#create-and-deploy-configmap-object.

**Comment by spkesan** [comment]
@akhilles 
Thanks for reporting this. I have fixed the example doc.
`on-start.sh` and `install.sh` scripts are now part of [init container image (aerospike/aerospike-kubernetes-init)](https://github.com/aerospike/aerospike-kubernetes-init)

So they are no longer required in `configMap`. Just `aerospike.template.conf` in the `configMap` is enough. Please check the updated docs. 
Thanks again for pointing it out.

You can also use Aerospike Helm Chart to try out the same example.
Here's a link to our website documentation https://www.aerospike.com/docs/deploy_guides/kubernetes/examples/index.html

The website documentation uses Enterprise Edition chart, however you can do the same procedure using Community Edition chart.

You can find the charts on [Helm Hub](https://hub.helm.sh/charts/aerospike) or here in this GitHub repository under `helm/` directory.
