### ISSUE TITLE
Remove `transaction-queues` from config file

### ISSUE THREAD

**Issue by akhilles** [aerospike/aerospike-kubernetes#22]
When following the steps at https://github.com/aerospike/aerospike-kubernetes/tree/master/examples/storage-engine-device, I encountered:
```
link eth0 state up
link eth0 state up in 0
May 28 2020 00:15:23 GMT: CRITICAL (config): (cfg.c:1407) line 10 :: 'transaction-queues' is obsolete - please configure 'service-threads' carefully
May 28 2020 00:15:23 GMT: WARNING (as): (signal.c:161) SIGINT received, shutting down Aerospike Community Edition build 5.0.0.4 os debian9
May 28 2020 00:15:23 GMT: WARNING (as): (signal.c:164) startup was not complete, exiting immediately
```

I was able to deploy successfully after removing the following lines from `aerospike.template.conf`:
```
	transaction-queues ${TRANSACTION_QUEUES}
	transaction-threads-per-queue ${TRANSACTION_THREADS_PER_QUEUE}
```

**Comment by spkesan** [comment]
Thanks @akhilles for pointing it out. These two configs `transaction-queues` and `transaction-threads-per-queue` has been removed since aerospike server version 4.7+. I have fixed the examples.
