### ISSUE TITLE
UDF support

### ISSUE THREAD

**Issue by Danny-m08** [aerospike/aerospike-kubernetes#23]
Can we implement an entry in the values.yaml that will allow users to mount UDF lua files and register them upon initialization?

**Comment by spkesan** [comment]
Hi @Danny-m08 
Wouldn't it be easier to register the UDFs from client or application ?

Or,
You can also mount volumes like [hostPath](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath), [nfs](https://kubernetes.io/docs/concepts/storage/volumes/#nfs) etc. (there's more) to share UDF lua files and register them using `aql` with `kubectl exec`

[configure static volumes in aerospike helm chart](https://github.com/aerospike/aerospike-kubernetes/blob/7a0d9c4ea892222cf842102da1e76a0856801032/helm/values.yaml#L189-L197)

**Comment by Danny-m08** [comment]
Yes that 2nd option is more in line with what I was looking for. I must have overlooked that entry in the values file
