### ISSUE TITLE
Helm - last updates "Allow liveness... configurable" not released

### ISSUE THREAD

**Issue by harscoet** [aerospike/aerospike-kubernetes#27]
The last commit to be able to configure probes is not released, actually when we pull the chart from the repository https://aerospike.github.io/aerospike-kubernetes we have an old version

I just created a PR if you need one https://github.com/aerospike/aerospike-kubernetes/pull/29

**Comment by spkesan** [comment]
@harscoet 
Thanks for the patience.
The [latest helm chart release](https://github.com/aerospike/aerospike-kubernetes/releases/tag/1.5.0) allows to configure livenessProbe parameters. Closing this issue.
